### ISSUE TITLE
Errors with the testing codes of "Quick Start" 

### ISSUE THREAD

**Issue by XiaohaoSun** [X-rayLaser/multi-directional-mdrnn#2]
Hi, 

Thank you for sharing the MDRNN code. I am new to tensorflow and want to use MDRNN for my projects. I just downloaded the code and was running the testing code of Quick Start section. I tested the code in Anaconda and Spyder. First I got some errors with the simplest use:
```
rnn = MDRNN(units=16, input_shape=(5, 4, 10), activation='tanh', return_sequences=True)
output = rnn(np.zeros((1, 5, 4, 10)))
```
Later I found adding `tf.compat.v1.enable_eager_execution()` at the beginning makes it work fine.

However, when I was running
```
model = tf.keras.Sequential() 
model.add(MDRNN(units=16, input_shape=(2, 3, 6), activation='tanh'))
```
I got long error information. I am not sure which parts are important and so pasted the most of the information below:
```
WARNING:tensorflow:Entity <bound method BaseMDRNN.call of <mdrnn._layers.simple_mdrnn.MDRNN object at 0x00000225EBAB4B08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BaseMDRNN.call of <mdrnn._layers.simple_mdrnn.MDRNN object at 0x00000225EBAB4B08>>: AttributeError: module 'gast' has no attribute 'Str'

Traceback (most recent call last):
  File "D:\multi-directional-mdrnn-master\trial0_quick_start.py", line 24, in <module>
    model.add(MDRNN(units=16, input_shape=(2, 3, 6), activation='tanh'))

  File "C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 174, in add
    layer(x)

  File "C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 629, in __call__
    outputs = call_fn(inputs, *args, **kwargs)

  File "C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))

TypeError: in converted code:

    D:\multi-directional-mdrnn-master\mdrnn\_layers\simple_mdrnn.py:95 call
        outputs = self._make_graph(inp, initial_state)
    D:\multi-directional-mdrnn-master\mdrnn\_layers\simple_mdrnn.py:117 _make_graph
        outputs = self._create_grid(grid_shape=grid_shape, tensor_shape=tensor_shape)
    D:\multi-directional-mdrnn-master\mdrnn\_layers\simple_mdrnn.py:61 _create_grid
        return TensorGrid(grid_shape=grid_shape, tensor_shape=tensor_shape)
    D:\multi-directional-mdrnn-master\mdrnn\_util\grids.py:80 __init__
        zeros_tensor = tf.zeros(shape=tensor_shape)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\ops\array_ops.py:1880 zeros
        shape = ops.convert_to_tensor(shape, dtype=dtypes.int32)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py:1087 convert_to_tensor
        return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py:1145 convert_to_tensor_v2
        as_ref=False)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py:1224 internal_convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\constant_op.py:305 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\constant_op.py:246 constant
        allow_broadcast=True)
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\constant_op.py:284 _constant_impl
        allow_broadcast=allow_broadcast))
    C:\Users\xsun403\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\tensor_util.py:467 make_tensor_proto
        nparray = np.array(values, dtype=np_dt)

    TypeError: __int__ returned non-int (type NoneType)
```

Sorry for the long post, and I appreciate all the help!

Xiaohao

**Comment by XiaohaoSun** [comment]
I think these errors are because I installed TensorFlow 1.x, I thought it was TF 2.x though. I re-installed TensorFlow using pip and the version is now shown as 2.8.0 and the testing codes work fine now!
